#' @include LongitudinalRandomSlopeCov.R
#' @include LongitudinalSteinFojo.R
NULL

#' Stein-Fojo longitudinal model with subject-level covariates
#'
#' Models the log-normal distribution parameters for baseline, shrinkage, and
#' growth using separate subject-level covariate predictors.
#'
#' @section Available Links:
#' - [`linkDSLD()`]
#' - [`linkTTG()`]
#' - [`linkIdentity()`]
#' - [`linkGrowth()`]
#' - [`linkShrinkage()`]
#'
#' @exportClass LongitudinalSteinFojoCov
.LongitudinalSteinFojoCov <- setClass(
    Class = "LongitudinalSteinFojoCov",
    contains = "LongitudinalModel",
    slots = c(
        mu_b_formula = "formula",
        omega_b_formula = "formula",
        mu_s_formula = "formula",
        omega_s_formula = "formula",
        mu_g_formula = "formula",
        omega_g_formula = "formula",
        mu_b_parametrization = "character",
        omega_b_parametrization = "character",
        mu_s_parametrization = "character",
        omega_s_parametrization = "character",
        mu_g_parametrization = "character",
        omega_g_parametrization = "character",
        centred_baseline = "logical"
    )
)

#' Construct a Stein-Fojo model with subject-level covariates
#'
#' The intercept column generated by each formula is removed. The separately
#' specified intercept parameter is the reference-level value except for the
#' `exponential` parametrization, whose reference-level value is one.
#' `linear` uses `intercept + X beta`, `proportional` uses
#' `intercept * (1 + X beta)`, `exponential` uses
#' `intercept ^ (X beta)`, and `log-linear` uses
#' `exp(intercept + X beta)`.
#'
#' @param mu_b_formula,omega_b_formula,mu_s_formula,omega_s_formula,mu_g_formula,omega_g_formula
#'   One-sided formulas evaluated in the subject-level data.
#' @param mu_b_parametrization,omega_b_parametrization,mu_s_parametrization,omega_s_parametrization,mu_g_parametrization,omega_g_parametrization
#'   Predictor parametrizations.
#' @param mu_b_intercept_prior,mu_b_coefficients_prior Priors for the baseline log-mean predictor.
#' @param omega_b_intercept_prior,omega_b_coefficients_prior Priors for the baseline log-SD predictor.
#' @param mu_s_intercept_prior,mu_s_coefficients_prior Priors for the shrinkage log-mean predictor.
#' @param omega_s_intercept_prior,omega_s_coefficients_prior Priors for the shrinkage log-SD predictor.
#' @param mu_g_intercept_prior,mu_g_coefficients_prior Priors for the growth log-mean predictor.
#' @param omega_g_intercept_prior,omega_g_coefficients_prior Priors for the growth log-SD predictor.
#' @param sigma Prior for the observation-error standard deviation.
#' @param scaled_variance Whether to use multiplicative observation error.
#' @param centred_baseline Whether to use a centred parameterization for the
#'   subject-specific baseline effects. Shrinkage and growth remain
#'   non-centred.
#'
#' @returns A `LongitudinalSteinFojoCov` object.
#' @export
#'
#' @examples
#' LongitudinalSteinFojoCov()
LongitudinalSteinFojoCov <- function(
    mu_b_formula = ~study,
    omega_b_formula = ~study,
    mu_s_formula = ~arm,
    omega_s_formula = ~arm,
    mu_g_formula = ~arm,
    omega_g_formula = ~arm,
    mu_b_parametrization = "linear",
    omega_b_parametrization = "log-linear",
    mu_s_parametrization = "linear",
    omega_s_parametrization = "log-linear",
    mu_g_parametrization = "linear",
    omega_g_parametrization = "log-linear",
    mu_b_intercept_prior = prior_normal(log(60), 1),
    mu_b_coefficients_prior = prior_normal(0, 1),
    omega_b_intercept_prior = prior_normal(log(0.2), 1),
    omega_b_coefficients_prior = prior_normal(0, 1),
    mu_s_intercept_prior = prior_normal(log(0.5), 1),
    mu_s_coefficients_prior = prior_normal(0, 1),
    omega_s_intercept_prior = prior_normal(log(0.2), 1),
    omega_s_coefficients_prior = prior_normal(0, 1),
    mu_g_intercept_prior = prior_normal(log(0.3), 1),
    mu_g_coefficients_prior = prior_normal(0, 1),
    omega_g_intercept_prior = prior_normal(log(0.2), 1),
    omega_g_coefficients_prior = prior_normal(0, 1),
    sigma = prior_lognormal(log(0.1), 1),
    scaled_variance = FALSE,
    centred_baseline = FALSE
) {
    assert_flag(centred_baseline)

    formula_names <- c(
        "mu_b", "omega_b", "mu_s", "omega_s", "mu_g", "omega_g"
    )
    formulas <- mget(paste0(formula_names, "_formula"), inherits = FALSE)
    formulas <- Map(.validate_covariate_formula, formulas, paste0(formula_names, "_formula"))
    names(formulas) <- formula_names

    parametrizations <- mget(
        paste0(formula_names, "_parametrization"),
        inherits = FALSE
    )
    parametrizations <- Map(
        .validate_covariate_parametrization,
        parametrizations,
        paste0(formula_names, "_parametrization")
    )
    names(parametrizations) <- formula_names

    for (name in c("omega_b", "omega_s", "omega_g")) {
        prior_name <- paste0(name, "_intercept_prior")
        assign(
            prior_name,
            .positive_intercept_prior(
                get(prior_name, inherits = FALSE),
                parametrizations[[name]],
                positive = parametrizations[[name]] != "log-linear"
            )
        )
    }
    for (name in c("mu_b", "mu_s", "mu_g")) {
        prior_name <- paste0(name, "_intercept_prior")
        assign(
            prior_name,
            .positive_intercept_prior(
                get(prior_name, inherits = FALSE),
                parametrizations[[name]]
            )
        )
    }
    sigma <- set_limits(sigma, lower = getOption("jmpost.double_eps"))

    stan_predictors <- lapply(formula_names, function(name) {
        .covariate_predictor_stan(
            paste0("lm_sfc_", name),
            parametrizations[[name]]
        )
    })
    names(stan_predictors) <- formula_names
    stan <- StanModule(decorated_render(
        .x = read_stan("lm-stein-fojo-cov/model.stan"),
        scaled_variance = scaled_variance,
        centred_baseline = centred_baseline,
        mu_b_predictor = stan_predictors$mu_b,
        omega_b_predictor = stan_predictors$omega_b,
        mu_s_predictor = stan_predictors$mu_s,
        omega_s_predictor = stan_predictors$omega_s,
        mu_g_predictor = stan_predictors$mu_g,
        omega_g_predictor = stan_predictors$omega_g
    ))

    parameters <- list()
    for (name in formula_names) {
        parameters <- append(parameters, list(
            Parameter(
                name = paste0("lm_sfc_", name, "_intercept"),
                prior = get(paste0(name, "_intercept_prior"), inherits = FALSE)
            ),
            Parameter(
                name = paste0("lm_sfc_", name, "_coefficients"),
                prior = get(paste0(name, "_coefficients_prior"), inherits = FALSE),
                size = paste0("p_lm_sfc_", name)
            )
        ))
    }
    baseline_parameter <- if (centred_baseline) {
        Parameter(
            name = "lm_sfc_psi_b",
            prior = set_limits(
                prior_init_only(prior_lognormal(
                    .predictor_reference_value(
                        mu_b_intercept_prior,
                        parametrizations$mu_b
                    ),
                    .predictor_reference_value(
                        omega_b_intercept_prior,
                        parametrizations$omega_b
                    )
                )),
                lower = getOption("jmpost.double_eps")
            ),
            size = "n_subjects"
        )
    } else {
        Parameter(
            name = "lm_sfc_eta_tilde_b",
            prior = prior_std_normal(),
            size = "n_subjects"
        )
    }
    parameters <- append(parameters, list(
        Parameter(name = "lm_sfc_sigma", prior = sigma),
        baseline_parameter,
        Parameter(
            name = "lm_sfc_eta_tilde_s",
            prior = prior_std_normal(),
            size = "n_subjects"
        ),
        Parameter(
            name = "lm_sfc_eta_tilde_g",
            prior = prior_std_normal(),
            size = "n_subjects"
        )
    ))

    .LongitudinalSteinFojoCov(
        LongitudinalModel(
            name = "Stein-Fojo with Covariates",
            stan = merge(stan, StanModule("lm-stein-fojo/functions.stan")),
            parameters = do.call(ParameterList, parameters),
            scaled_variance = scaled_variance
        ),
        mu_b_formula = formulas$mu_b,
        omega_b_formula = formulas$omega_b,
        mu_s_formula = formulas$mu_s,
        omega_s_formula = formulas$omega_s,
        mu_g_formula = formulas$mu_g,
        omega_g_formula = formulas$omega_g,
        mu_b_parametrization = parametrizations$mu_b,
        omega_b_parametrization = parametrizations$omega_b,
        mu_s_parametrization = parametrizations$mu_s,
        omega_s_parametrization = parametrizations$omega_s,
        mu_g_parametrization = parametrizations$mu_g,
        omega_g_parametrization = parametrizations$omega_g,
        centred_baseline = centred_baseline
    )
}

#' @export
#'
#' @returns A `StanModule` object containing the generated-quantities code.
enableGQ.LongitudinalSteinFojoCov <- function(
    object,
    generator = NULL,
    type = NULL,
    ...
) {
    include_subject <- identical(type, "longitudinal") &&
        is(generator, "QuantityGeneratorSubject")
    include_population <- identical(type, "longitudinal") &&
        is(generator, "QuantityGeneratorPopulation")
    predictor <- function(name) {
        .covariate_predictor_stan(
            paste0("lm_sfc_", name),
            slot(object, paste0(name, "_parametrization")),
            design_prefix = paste0("gq_lm_sfc_", name),
            n_rows = "gq_n_quant"
        )
    }
    StanModule(decorated_render(
        .x = read_stan("lm-stein-fojo-cov/quantities.stan"),
        include_gq_longitudinal_idv = include_subject,
        include_gq_longitudinal_pop = include_population,
        mu_b_population_predictor = predictor("mu_b"),
        mu_s_population_predictor = predictor("mu_s"),
        mu_g_population_predictor = predictor("mu_g")
    ))
}

#' @rdname gq_population_stan_data
#' @export
gq_population_stan_data.LongitudinalSteinFojoCov <- function(
    object,
    model,
    data = NULL,
    ...
) {
    result <- list(
        declarations = paste(
            "matrix[gq_n_quant, p_lm_sfc_mu_b] gq_lm_sfc_mu_b_design;",
            "matrix[gq_n_quant, p_lm_sfc_mu_s] gq_lm_sfc_mu_s_design;",
            "matrix[gq_n_quant, p_lm_sfc_mu_g] gq_lm_sfc_mu_g_design;",
            sep = "\n"
        ),
        data = list()
    )
    if (!is.null(data)) {
        assert_that(
            !is.null(object@newdata) &&
                nrow(object@newdata) == length(object@times),
            msg = paste0(
                "Population quantities for `LongitudinalSteinFojoCov` ",
                "require `GridPopulation(newdata = ...)`"
            )
        )
        result$data <- .stein_fojo_cov_population_stan_data(
            model,
            data@subject,
            object@newdata
        )
    }
    result
}

#' @export
#'
#' @returns The longitudinal model with its link-related Stan code enabled.
enableLink.LongitudinalSteinFojoCov <- function(object, ...) {
    object@stan <- merge(
        object@stan,
        StanModule("lm-stein-fojo-cov/link.stan")
    )
    object
}

#' @export
#' @returns A `LinkComponent` object.
linkDSLD.LongitudinalSteinFojoCov <- function(prior = prior_normal(0, 2), model, ...) {
    LinkComponent(
        key = "link_dsld",
        stan = StanModule("lm-stein-fojo/link_dsld.stan"),
        prior = prior
    )
}

#' @export
#' @returns A `LinkComponent` object.
linkTTG.LongitudinalSteinFojoCov <- function(prior = prior_normal(0, 2), model, ...) {
    LinkComponent(
        key = "link_ttg",
        stan = StanModule("lm-stein-fojo/link_ttg.stan"),
        prior = prior
    )
}

#' @export
#' @returns A `LinkComponent` object.
linkIdentity.LongitudinalSteinFojoCov <- function(prior = prior_normal(0, 2), model, ...) {
    LinkComponent(
        key = "link_identity",
        stan = StanModule("lm-stein-fojo/link_identity.stan"),
        prior = prior
    )
}

#' @export
#' @returns A `LinkComponent` object.
linkGrowth.LongitudinalSteinFojoCov <- function(prior = prior_normal(0, 2), model, ...) {
    LinkComponent(
        key = "link_growth",
        stan = StanModule("lm-stein-fojo/link_growth.stan"),
        prior = prior
    )
}

#' @export
#' @returns A `LinkComponent` object.
linkShrinkage.LongitudinalSteinFojoCov <- function(prior = prior_normal(0, 2), model, ...) {
    LinkComponent(
        key = "link_shrinkage",
        stan = StanModule("lm-stein-fojo/link_shrinkage.stan"),
        prior = prior
    )
}

#' @rdname getPredictionNames
#' @export
getPredictionNames.LongitudinalSteinFojoCov <- function(object, ...) c("b", "s", "g")

#' @rdname getRandomEffectsNames
#' @export
getRandomEffectsNames.LongitudinalSteinFojoCov <- function(object, ...) {
    c(b = "lm_sfc_psi_b", s = "lm_sfc_psi_s", g = "lm_sfc_psi_g")
}

#' @rdname longitudinal_model_stan_data
#' @keywords internal
#' @export
longitudinal_model_stan_data.LongitudinalSteinFojoCov <- function(model, subject) {
    subject_data <- as.data.frame(harmonise(subject))
    parameter_names <- c("mu_b", "omega_b", "mu_s", "omega_s", "mu_g", "omega_g")
    designs <- lapply(parameter_names, function(name) {
        .covariate_design_matrix(
            slot(model, paste0(name, "_formula")),
            subject_data,
            paste0(name, "_formula")
        )
    })
    names(designs) <- parameter_names
    result <- list()
    for (name in parameter_names) {
        result[[paste0("p_lm_sfc_", name)]] <- ncol(designs[[name]])
        result[[paste0("lm_sfc_", name, "_design")]] <- designs[[name]]
    }
    result
}

#' @rdname required_longitudinal_covs
#' @export
required_longitudinal_covs.LongitudinalSteinFojoCov <- function(object, ...) {
    unique(unlist(lapply(c("mu_b", "mu_s", "mu_g"), function(name) {
        all.vars(slot(object, paste0(name, "_formula")))
    })))
}

#' @rdname required_simulation_covariates
#' @export
required_simulation_covariates.LongitudinalSteinFojoCov <- function(
    object,
    ...
) {
    unique(unlist(lapply(
        c("mu_b", "omega_b", "mu_s", "omega_s", "mu_g", "omega_g"),
        function(name) all.vars(slot(object, paste0(name, "_formula")))
    )))
}

#' Create covariate Stein-Fojo population-prediction Stan data
#'
#' @keywords internal
#' @returns A named list of population generated-quantities design matrices.
.stein_fojo_cov_population_stan_data <- function(model, subject, newdata) {
    subject_data <- as.data.frame(harmonise(subject))
    parameter_names <- c("mu_b", "mu_s", "mu_g")
    result <- lapply(parameter_names, function(name) {
        .covariate_prediction_design_matrix(
            slot(model, paste0(name, "_formula")),
            newdata,
            subject_data,
            paste0(name, "_formula")
        )
    })
    names(result) <- paste0("gq_lm_sfc_", parameter_names, "_design")
    result
}
