.mcmc_options <- setClass(Class = "mcmc_options",
                          slots = c(data = "list",
                                    seed = "integer",
                                    refresh = "integer",
                                    init = "list",
                                    save_latent_dynamics = "logical",
                                    output_dir = "string",
                                    output_basename = "string",
                                    sig_figs = "integer",
                                    chains = "integer",
                                    parallel_chains = "integer",
                                    chain_ids = "integer",
                                    threads_per_chain = "integer",
                                    opencl_ids = "integer",
                                    iter_warmup = "integer",
                                    iter_sampling = "integer",
                                    save_warmup = "logical",
                                    thin = "integer",
                                    max_treedepth = "integer",
                                    adapt_engaged = "logical",
                                    adapt_delta = "real",
                                    step_size = "real",
                                    init_buffer = "integer",
                                    term_buffer = "integer",
                                    window = "integer",
                                    fixed_param = "logical",
                                    show_messages = "logical",
                                    diagnostics = "character",
                                    ))


McmcOptions <- function(data = NULL,
                        seed = NULL,
                        refresh = NULL,
                        init = NULL,
                        save_latent_dynamics = FALSE,
                        output_dir = NULL,
                        output_basename = NULL,
                        sig_figs = NULL,
                        chains = 4,
                        parallel_chains = getOption("mc.cores", 1),
                        chain_ids = seq_len(chains),
                        threads_per_chain = NULL,
                        opencl_ids = NULL,
                        iter_warmup = NULL,
                        iter_sampling = NULL,
                        save_warmup = FALSE,
                        thin = NULL,
                        max_treedepth = NULL,
                        adapt_engaged = TRUE,
                        adapt_delta = NULL,
                        step_size = NULL,
                        metric = NULL,
                        metric_file = NULL,
                        inv_metric = NULL,
                        init_buffer = NULL,
                        term_buffer = NULL,
                        window = NULL,
                        fixed_param = FALSE,
                        show_messages = TRUE,
                        diagnostics = c("divergences", "treedepth", "ebfmi"),
                        cores = NULL,
                        num_cores = NULL,
                        num_chains = NULL,
                        num_warmup = NULL,
                        num_samples = NULL,
                        validate_csv = NULL,
                        save_extra_diagnostics = NULL,
                        max_depth = NULL,
                        stepsize = NULL){

    prep_data <- data_prep(data)

    .mcmc_options(data = prep_data@data,
                  seed = seed,
                  refresh = refresh,
                  init = init,
                  save_latent_dynamics = save_latent_dynamics,
                  output_dir = output_dir,
                  output_basename = output_basename,
                  sig_figs = sig_figs,
                  chains = chains,
                  parallel_chains = parallel_chains,
                  chain_ids = chain_ids,
                  threads_per_chain = threads_per_chain,
                  opencl_ids = opencl_ids,
                  iter_warmup = iter_warmup,
                  iter_sampling = iter_sampling,
                  save_warmup = save_warmup,
                  thin = thin,
                  max_treedepth = max_treedepth,
                  adapt_engaged = adapt_engaged,
                  adapt_delta = adapt_delta,
                  step_size = step_size,
                  init_buffer = init_buffer,
                  term_buffer = term_buffer,
                  window = window,
                  fixed_param = fixed_param,
                  show_messages = show_messages,
                  diagnostics = diagnostics)


}



