---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - lintr-test
  workflow_dispatch:

  # Rerun workflows once pkgdown has finished running, to add coverage
  # and unit test report to gh-pages branch.
  workflow_run:
    workflows: ["Docs 📚"]
    types:
      - completed

jobs:
  audit:
    name: Audit Dependencies 🕵️‍♂️
    uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@main
  r-cmd:
    name: R CMD Check 🧬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
        JMPOST_CACHE_DIR=${{ github.workspace }}/.cache
      additional-caches: |
        ${{ github.workspace }}/.cache
  coverage:
    name: Coverage 📔
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
  ### Disabled pending https://github.com/insightsengineering/idr-tasks/issues/667
  linter:
    # if: github.event_name == 'pull_request'
    name: SuperLinter 🦸‍♀️
    uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@update-lintr
  roxygen:
    name: Roxygen 🅾
    uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      auto-update: true
  gitleaks:
    name: gitleaks 💧
    uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@main
  spelling:
    if: github.event_name == 'pull_request'
    name: Spell Check 🆎
    uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
  links:
    if: github.event_name == 'pull_request'
    name: Check URLs 🌐
    uses: insightsengineering/r.pkg.template/.github/workflows/links.yaml@main
  version:
    name: Version Check 🏁
    uses: insightsengineering/r.pkg.template/.github/workflows/version.yaml@main
  licenses:
    name: License Check 🃏
    uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@main
  grammar:
    if: github.event_name == 'pull_request'
    name: Grammar Check 🔤
    uses: insightsengineering/r.pkg.template/.github/workflows/grammar.yaml@main
