on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: on_push_pull

jobs:
  testthat:
    runs-on: ubuntu-latest

    name: jmpost-latest-testthat
    
    container:
      image: ghcr.io/genentech/jmpost:latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: testthat
        run: |
          options(crayon.enabled = TRUE, cli.dynamic = FALSE)
          devtools::test(stop_on_failure = TRUE, reporter = testthat::CheckReporter)
        shell: Rscript {0}
  
  is-documented:
    runs-on: ubuntu-latest
    name: check-is-documented
    container:
      image: ghcr.io/genentech/jmpost:latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Document Code
        run: |
          options(crayon.enabled = TRUE, cli.dynamic = FALSE)
          devtools::document()
        shell: Rscript {0}
      
      - name: Check Is Clean
        shell: bash
        run: |
          git config --global --add safe.directory $(pwd)
          git status
          if [ -z "$(git status --porcelain)" ]; then
            echo "Is Clean"
          else
            echo "Changed Detected"
            exit 2
          fi

